[build]
  base = "."
  command = "npm install && npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = true

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
