[build]
  base = "."
  command = "npm install && npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = true

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
